### ISSUE TITLE
add support for `scope`

### ISSUE THREAD

**Issue by gconnolly** [auth0/angular-auth0#14]
The current version of `angular-auth0` does not support `scope` on init and will silently drop the configuration value. 

- See Auth0 code here: https://github.com/auth0/auth0.js/blob/v7/index.js#L164
- See commit https://github.com/gconnolly/angular-auth0/commit/192df9dea6715eb7f4da52a296d4f2023244ffd3

Rather than one-off supporting the scope configuration, it would be ideal to passthrough all configuration from the wrapper to the Auth0 constructor. This would also allow for the support of other Auth0 configuration:

- `audience`, `sendSDKClientInfo`, `useCordovaSocialPlugins`, `forceJSONP`: https://github.com/auth0/auth0.js/blob/v7/index.js#L148-L167

**Comment by chenkie** [comment]
merged in your PR for the fix, thanks :)
