### ISSUE TITLE
[Question] user_metadata is not included, if angular.client.userInfo is called

### ISSUE THREAD

**Issue by mgruel** [auth0/angular-auth0#16]
I try to load the userInfo via `angularAuth0.client.userInfo` with the available accessToken.

In the provided callback, the returned userInfo object does not include the existing `user_metadata`, 
which is visible in the users detail view on the dashboard.

Can you point me to the appropriate function of the `angularAuth0` object to retrieve the full user profile with the existing `user_metadata`?

Best regards
Meykel

---
*Packages*
- angular: 1.5.11,
- auth0: 8.7.0 (retrieved from cdn)
- angular-auth0: 2.0.0-beta.2

**Comment by chenkie** [comment]
This is by design :) More info in this issue: https://github.com/auth0/auth0.js/issues/433#issuecomment-305519595

**Comment by mgruel** [comment]
Thank you the information, will look into the comment.
