### ISSUE TITLE
Problems using package with browserify/webpack workflow

### ISSUE THREAD

**Issue by robations** [auth0/angular-auth0#19]
It seems like the package assumes everything will be loaded into global scope, even if you `require("angular-auth0")`, this line assumes that `auth0` is available from global scope:

      var Auth0Js = new auth0.WebAuth(this.config);

([see v2 branch here](https://github.com/auth0/angular-auth0/blob/v2/dist/angular-auth0.js#L23))

And also that `angular` is a global. Is there a universal module syntax that would allow different ways of handling this?

**Comment by chenkie** [comment]
Just switched to webpack for 2.0.0-beta.3. Can you try it out and see if it solves your issue?

**Comment by joshcanhelp** [comment]
This issue has been closed as stale because it has not had recent activity. If you have not received a response for our team (apologies for the delay), please reply with any additional information or a ping. Thank you for your contribution!
