### ISSUE TITLE
cannot load module

### ISSUE THREAD

**Issue by bennyAG** [auth0/angular-auth0#21]
Module 'auth0.auth0' is not available! You either misspelled the module name or forgot to load it

I loaded libraries in index file without error.
<script src="lib/auth0.js/build/auth0.js"></script>
<script src="lib/auth0-angular/build/auth0-angular.js"></script>

**Comment by chenkie** [comment]
it looks like you've got the wrong import path. It should be

```html
<script src="lib/angular-auth0/dist/angular-auth0.js"></script>
```

It should be noted that there is also a project, now deprecated, called [auth0-angular](https://github.com/auth0/auth0-angular). Is it possible that you're trying to use that one and not angular-auth0?

**Comment by joshcanhelp** [comment]
This issue has been closed as stale because it has not had recent activity. If you have not received a response for our team (apologies for the delay), please reply with any additional information or a ping. Thank you for your contribution!
