### ISSUE TITLE
Request: Promisify methods, i.e .return $q promises

### ISSUE THREAD

**Issue by tomyam1** [auth0/angular-auth0#24]
You can support both methods simultaneously, e.g. as done in bluebird's [asCallback](http://bluebirdjs.com/docs/api/ascallback.html)

**Comment by chenkie** [comment]
We could look at this but I might like to keep it as close to auth0.js (which only uses callbacks) as possible. It is just a thin wrapper for auth0.js after all. 

Are you able to promisify the wrapper on your end?

**Comment by tomyam1** [comment]
Sure, we already do it.
It just felt unnatural for an angular module to use callbacks and not support promises.
I suspect most of the users do it as well.

Feel free the close the issue if you'd rather not do it.

**Comment by joshcanhelp** [comment]
This issue has been closed as stale because it has not had recent activity. If you have not received a response for our team (apologies for the delay), please reply with any additional information or a ping. Thank you for your contribution!
