### ISSUE TITLE
Problems with webpack 1 and ES6

### ISSUE THREAD

**Issue by jfmercer** [auth0/angular-auth0#9]
With webpack 1 and ES6, and I cannot replace `auth0-angular` with `angular-auth0`. 

Previously, my auth0 module looked like this:

```js
import * as angular from 'angular';

import 'auth0-js';
import auth0 from 'auth0-angular';

export default angular.module('authZero', [
  auth0
]).name;
```

In webpack, I used to the `ProvidePlugin` to make `Auth0` globally available on the `window` object:

```js
new webpack.ProvidePlugin({
  'window.Auth0': 'auth0-js'
})
```

With `angular-auth0`, depending on my configuration, I get a variety of errors. I compared `angular-auth0` with `auth0-angular` to see why one worked with webpack module bundling & the other did not. I suspect that the difference is that `auth0-angular` [uses `node`'s standard `module.exports` syntax](https://github.com/auth0/auth0-angular/blob/master/index.js#L2):

```js
require('./build/auth0-angular.js');
module.exports = 'auth0';
```

Could `angular-auth0` be changed to add compatibility standard node module bundling tools, such as webpack? I could put in a PR for this if you think it worthwhile.

**Comment by chenkie** [comment]
Definitely, PRs are welcome :)

**Comment by samber** [comment]
Is there any news about this issue ?

How can I use angular-auth0 with webpack ?

**Comment by jfmercer** [comment]
@chenkie Please see #11, which will probably solve this issue.

**Comment by chenkie** [comment]
Thanks for your PR @jfmercer. Merged.
